CREATE DATABASE ToDoListCamiloGomez
GO

USE [ToDoListCamiloGomez]
GO

CREATE TABLE Tasks
(
	Id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	State INT NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	CreatedBy NVARCHAR(100) NOT NULL,
	ModifiedBy NVARCHAR(100) NULL,
	CreatedAt DATETIME NOT NULL,
	ModifiedAt DATETIME NULL,
	IsDeleted BIT NOT NULL
)

CREATE TABLE Users
(
	Id BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Username NVARCHAR(50) NOT NULL,
	PasswordHash NVARCHAR(256) NOT NULL,
	CreatedAt DATETIME NOT NULL,
	ModifiedAt DATETIME NULL,
	IsDeleted BIT NOT NULL
)